config/routes.rb
Rails.application.routes.draw do
  
  root 'gyms#index'

  resources :gyms 
  resources :reviews

  get 'sessions/new'

  get 'sessions/create'
  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/signup", to: "users#new", as: "signup"
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :users

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/gym.rb
class Gym < ActiveRecord::Base
	has_many :reviews, dependent: :destroy

	
	reverse_geocoded_by :lat, :long, 
	:address => :address, :latitude => :lat, :longitude => :long 
	# after_validation :reverse_geocode, :geocode
	# after_update :all_total_ratings

	def avg_rating(attribute)
		if reviews.none?
		  val = 0
		else 
		  val = reviews.average(attribute)
		end
		return val
	end

	def all_total_ratings
		totals = self.reviews.map { |review| review.total_rating }
		grand_total = (totals.reduce(:+) / self.reviews.length)
		self.total_rating = grand_total
		p "in all total_ratings" * 100
		self.save
	end

	# def best_rating(attributes)
	# 	if reviews.none?
	# 	  val = 0
	# 	else 
	# 	  val = reviews.average(attributes)
	# 	end
	# 	return val
	# end

	def w_vs_m
		weightlifting = reviews.where(weightlifting_focus: true).count
    metcon =  reviews.where(metcon_focus: true).count
    
    if weightlifting  == 0 && metcon == 0
      @focus = ""
    elsif weightlifting > metcon
      @focus = "This gym focuses on weightlifting"
    elsif metcon > weightlifting
      @focus = "This gym focuses on metcon training"
    else 
      @focus = "This gym offers a balance of weightlifting and metcon training"
    end  
    return @focus
  end



	def self.search(search)

  	if search
    	self.where('name ILIKE ?', "%#{search}%")
  	else
    	self.all
  	end
	end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  
  def index
    # p request.location
    # if request.location.latitude == 0.0
      @latitude = 37.774929
      @longitude = -122.419416
    # else
    #   @latitude = request.location.latitude
    #   @longitude = request.location.longitude 
      
    

    if params[:search_name].present? && params[:search_city].present?
      @welcome = "Search results by name and city"
      @gyms = Gym.search(params[:search_name]).near(params[:search_city]).paginate(:page => params[:page], :per_page => 10) 
    elsif params[:search_city].present?
      @welcome = "Affiliates near #{params[:search_city]}"
      @gyms = Gym.near(params[:search_city], 50).paginate(:page => params[:page], :per_page => 10)
    elsif params[:search_name].present?
      @welcome = "Search results by name"
      @gyms = Gym.search(params[:search_name]).paginate(:page => params[:page], :per_page => 10)
    # else
    #   @welcome = "Locations close to you"
    #   @gyms = Gym.near([@latitude, @longitude], 20)
    else
      @welcome = "Top Rated Affiliates"
      @gyms = Gym.paginate(:page => params[:page], :per_page => 10).order("total_rating desc")
  
    end
  end

  def new
  end

  def create
  end

  def show
    @no_reviews = "There are no reviews yet, be the first to write one!"
    @user = current_user
    @gym = Gym.find(params[:id])
    @reviews = @gym.reviews
    @review = Review.new 
    #maps
    @gyms = Gym.all
    @hash = Gmaps4rails.build_markers(@gyms) do |gym, marker|
    marker.lat gym.lat
    marker.lng gym.long
end
  end

  def edit
      @user = current_user
      @gym = Gym.find(params[:id])
      if current_user
        if @gym.save
        end
      end
  end

  def update
    @review = Review.new
    @user = current_user
    @gym = Gym.find(params[:id])
    if current_user
      @gym.update_attributes(gym_params)
      @reviews = @gym.reviews
      render :show
    else
    end
  end

  def destroy
  end


  private

  def gym_params
    params.require(:gym).permit(:name, :website, :address, :phone)
  end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/destroy.html.erb
<div class="kettlebell-background"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-2">
	<!-- search bars -->
		    <div class="form-group">
		      <div class="input-group" >
		        <div class="form-inline">
		          <ul class="nav navbar-nav">
		            <li>
		              <%= form_tag(gyms_path, :method => "get", class: "navbar-form", id: "search-form") do %>
		              <div class="input-append">
		              <%= text_field_tag :search_name, params[:search_name], class: "form-control", autocomplete: "off", placeholder: "Search By Name" %>
		              <%= text_field_tag :search_city, params[:search_city], class: "form-control", autocomplete: "off", placeholder: "Search By Location" %>
		                <button class="btn btn-danger" type="submit"><i class="glyphicon glyphicon-search"></i></button>
		              </div>
		              <% end %>
		          </li>
		        </ul>
		      </div>
		    </div>
	 		 </div>
	 		</div>
	 	</div>	
	  <!-- end search bar -->
		<div class="row">
			<div class="col-md-7 col-md-offset-2">
				<h2><%= @welcome %></h2>
				<% @gyms.each do |gym| %>
				<div class="well well-sm">
					<div class="table-responsive">
						<div class="table table-condensed table-striped table-hover">
							<table style="width:100%">
					  		<tr> 
					  			<td><h3><%= link_to gym.name, gym_path(gym.id) %></h3></td>
									<% if params[:search_name].blank? && params[:search_city].blank? %>
					  				<td align="right"> </td>
					  			<% end %>
					  		</tr>
					  		<tr>
					  			<td><h4><%= gym.address %></h4></td>
					  			<td></td>
					  		</tr>
					  		<tr>
					  			<td><h4><%= link_to "#{gym.website}", "#{gym.website}", :target => "_blank"%></h4></td>
					  			<td align='right'><em><%= pluralize gym.reviews.size, 'review'%></em><br></td>
					  		</tr>
					 		</table>
					 	</div>
					 </div>
						<div class="row">
							<div class="col-xs-6 col-sm-3">
								Programming<br>
								<div class="star-rating-pro" data-score=<%= gym.avg_rating(:programming) %>></div>
							</div>
							<div class="col-xs-6 col-sm-3">
								Community<br>
								<div class="star-rating-val" data-score=<%= gym.avg_rating(:community) %>></div>
							</div>
							<div class="col-xs-6 col-sm-3">
								Value<br>
								<div class="star-rating-val" data-score=<%= gym.avg_rating(:value) %>></div>
							</div>
							<div class="col-xs-6 col-sm-3">
								Facility<br>
								<div class="star-rating-val" data-score=<%= gym.avg_rating(:facility) %>></div>
							</div>
						</div>
					</div>
				<% end %>	
			</div>	
		</div>
		<div id="infinite-scrolling">
		  <%= will_paginate @gyms %>
		</div>
	</div>

<!-- Script for displaying rating -->
<script>
	$('.star-rating-pro').raty({
		path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-fac').raty({
		path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-val').raty({
		path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-com').raty({
		path: '/assets/', 
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>

app/views/gyms/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-2">
    <%= form_for @gym do |g| %>
      <!-- error message -->
      <% if @gym_edit_error %>
        <div class="alert alert-info text-center alert-danger"><%= flash[:error] %></div>
      <% end %>
      <%= g.label :address %>
      <%= g.text_field :address, class: "form-control", autofocus: true %>
      <%= g.label :website %><!-- <button class='btn btn-default'>http://</button> -->
      <%= g.text_field :website, class: "form-control", placeholder: "www.crossfitgym.com" %>
      <br>
      <%= g.label :phone %>
      <%= g.text_field :phone, class: "form-control" %>
      <br>
      <span class="pull-right">
        <%= g.submit 'Submit', value: "Submit", class: "btn btn-primary" %> 
      </span>
    <% end %>
  </div>
</div>

app/views/gyms/index.html.erb
<div class="kettlebell-background"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
	<!-- search bars -->
		    <div class="form-group">
		      <div class="input-group" >
		        <div class="form-inline">
		          <ul class="nav navbar-nav">
		            <li>
		              <%= form_tag(gyms_path, :method => "get", class: "navbar-form", id: "search-form") do %>
		              <div class="input-append">
		              <%= text_field_tag :search_name, params[:search_name], class: "form-control", autocomplete: "off", placeholder: "Search By Name and/or" %>
		              <%= text_field_tag :search_city, params[:search_city], class: "form-control", autocomplete: "off", placeholder: "Search By Location" %>
		                <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
		              </div>
		              <% end %>
		          </li>
		        </ul>
		      </div>
		    </div>
	 		 </div>
	 		</div>
	 	</div>	
	  <!-- end search bar -->
		<div class="row">
			<div class="col-md-8">
				<h2><%= @welcome %></h2>
				<% @gyms.each do |gym| %>
				<div class="well well-sm">
					<div class="table-responsive">
						<div class="table table-condensed table-striped table-hover">
							<table style="width:100%">
					  		<tr> 
					  			<td><h3><%= link_to gym.name, gym_path(gym.id) %></h3></td>
									<% if params[:search_name].blank? && params[:search_city].blank? %>
					  				<td align="right"> </td>
					  			<% end %>
					  		</tr>
					  		<tr>
					  			<td><%= gym.address %></td>
					  			<td></td>
					  		</tr>
					  		<tr>
					  			<td><%= link_to "#{gym.website}", "#{gym.website}", :target => "_blank"%></td>
					  			<td align='right'><em><%= pluralize gym.reviews.size, 'review'%></em><br></td>
					  		</tr>
					 		</table>
					 	</div>
					 </div>
						<div class="row">
							<div class="col-xs-6 col-sm-3">
								Programming<br>
								<div class="star-rating-pro" data-score=<%= gym.avg_rating(:programming) %>></div>
							</div>
							<div class="col-xs-6 col-sm-3">
								Community<br>
								<div class="star-rating-val" data-score=<%= gym.avg_rating(:community) %>></div>
							</div>
							<div class="col-xs-6 col-sm-3">
								Value<br>
								<div class="star-rating-val" data-score=<%= gym.avg_rating(:value) %>></div>
							</div>
							<div class="col-xs-6 col-sm-3">
								Facility<br>
								<div class="star-rating-val" data-score=<%= gym.avg_rating(:facility) %>></div>
							</div>
						</div>
					</div>
				<% end %>	
			</div>	<!-- end col -->

			</div>
		</div>
		<div id="infinite-scrolling">
		  <%= will_paginate @gyms %>
		</div>
	</div>

<!-- Script for displaying rating -->
<script>
	$('.star-rating-pro').raty({
		// path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-fac').raty({
		// path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-val').raty({
		// path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-com').raty({
		// path: '/assets/', 
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>

app/views/gyms/show.html.erb
<div class="handstand-background"></div>
	<div class="container">
		<div class="row"><!-- row 1 -->
		<!-- Gym show  -->
			<div class="col-md-6"> <!-- column 1 -->
				<div class="well well-sm">
				<h3><%=@gym.name%></h3>
					<h5><% if @gym.address %> <%= @gym.address %> <% elsif @user %> <%= link_to 'Update Address', edit_gym_path %> <% else %> Log in to update address<% end %></h5>
					<h5><% if @gym.website %> <%= link_to "#{@gym.website}", "#{@gym.website}", :target => "_blank"%> <% elsif @user %> <%= link_to 'Update Website', edit_gym_path %> <% else %> Log in to update website <% end %></h5>
					<h5><% if @gym.phone %> <%= @gym.phone %> <% elsif @user %> <%= link_to 'Update Phone', edit_gym_path %> <% else %> Log in to update phone number <% end %></h5>
					<h5><%= @gym.w_vs_m %> <em class='pull-right'><%= pluralize @gym.reviews.size, 'review'%></em><br></h5>
		<div class="row">
				<div class="col-xs-6 col-sm-3">
					Programming<br>
					<div class="star-rating-pro" data-score=<%= @gym.avg_rating(:programming) %>></div>
				</div>
				<div class="col-xs-6 col-sm-3">
					Community<br>
					<div class="star-rating-val" data-score=<%= @gym.avg_rating(:community) %>></div>
				</div>
				<div class="col-xs-6 col-sm-3">
					Value<br>
					<div class="star-rating-val" data-score=<%= @gym.avg_rating(:value) %>></div>
				</div>
				<div class="col-xs-6 col-sm-3">
					Facility<br>
					<div class="star-rating-val" data-score=<%= @gym.avg_rating(:facility) %>></div>
				</div>
			</div>

			<% if !@user%>
			<span class="pull-left"><%= link_to 'Log in to Write a Review', '/login', class: 'btn btn-primary btn-sm'  %></span>
		<% end %>

		</div>
		
	</div>
	<div class="col-md-6"><!-- 	BEGIN map -->
		<div id="map" style='width: 100%; height: 210px;'></div>
		<!-- END map -->
	</div><!-- end column 1 -->
</div><!-- end row 1 -->

<!-- Begin of Review Show for User logged in-->
<% if @user %>
<div class="row"> <!-- row 3 -->
	<div class="col-md-6">
			<div class="well"> <!-- column 2 row 2 -->
				<h5 class="text-center">Write a Review</h5>
					<%= form_for @review do |r| %>
						<%= r.hidden_field :gym_id, :value => @gym.id %>
						<%= r.hidden_field :user_id, :value => @user.id %>
						<%= r.text_area :body, class: "form-control", autofocus: true, placeholder: "Tell us about your experience here!" %>
				<br>
				<div class="check-boxes">
					<div class="table-responsive">
						<div class="table table-condensed">
							<table style="width:100%">
				  			<tr>
				    			<td><%= r.check_box(:weightlifting_focus) %>Weightlifting Focus</td>
									<td><%= r.check_box(:metcon_focus) %> Metcon Focus</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
			<div class="ratings">
				<div class="row">
					<div class="col-xs-6 col-sm-3">
						Programming<br>
						<div id="star-rating-pro"></div>
					</div>
					<div class="col-xs-6 col-sm-3">
						Community<br>
						<div id="star-rating-com"></div>
					</div>
					<div class="col-xs-6 col-sm-3">
						Value<br>
						<div id="star-rating-val"></div>
					</div>
					<div class="col-xs-6 col-sm-3">
						Facility<br>
						<div id="star-rating-fac"></div>
					</div>
				</div>
				<br>
			</div>
			<div class="text-right">
				<%= r.submit 'review', value: "Post!", class: "btn btn-primary btn-sm" %>
			</div>
			<% end %> <!-- end form -->
		<!-- END OF NEW REVIEW FORM -->
			</div><!-- end well -->
		</div><!-- end col -->
			
	<% if @reviews.count < 1  %>
	<div class="col-md-6">
		<div class="well well-sm">
			<h3><center><%= @no_reviews %></center></h3>
		</div>
	</div>
	<% else %>
			<!-- Display Reviews -->
		<div class="col-md-6">
		<% @reviews.reverse.each do |review|  %>
			<div class="well well-sm">
				<% user_id = review.user_id %>
					<% author = User.find(user_id) %>
				<ul class='list-unstyled'>
					<li class='list-unstyled'>
						<h5>Posted by <%= author.username %> on <%= review.created_at.strftime("%B %d, %Y") %></h5>
						<h5><%= review.body %></h5>
							<div class="row">
								<div class="col-xs-6 col-sm-3">
									Programming<br>
									<div class="star-rating-pro" data-score=<%= review.programming %>></div>
								</div>
								<div class="col-xs-6 col-sm-3">
									Community<br>
									<div class="star-rating-com" data-score=<%= review.community %>></div>
								</div>
								<div class="col-xs-6 col-sm-3">
									Value<br>
									<div class="star-rating-fac" data-score=<%= review.facility %>></div>
								</div>
								<div class="col-xs-6 col-sm-3">
									Facility<br>
									<div class="star-rating-val" data-score=<%= review.value %>></div>
								</div>
							</div>
							<% if @user %>
							<span class="pull-right">
	      				<%= link_to '', "/reviews/#{review.id}/edit", class: 'ion ion-edit' %>
	     				</span>
	     				<% end %>					
	     		</li>
				</ul>
	  	</div> <!-- END WELL -->
	  	<% end %>
		</div> <!-- END COL--><!-- end of reviews show -->	
	</div> <!-- end of row 3 col 1 -->
	<% end %>

<!-- 	If no user logged in show these reviews -->
	<% else %>
	<div class="row review-row">
			<% if @reviews.count < 1  %>
		<div class="col-xs-12">
			<div class="well well-sm">
				<h3><center><%= @no_reviews %></center></h3>
			</div>
		</div>
			<% else %><!-- Display Reviews -->
		<div class="col-xs-12">
		
		<% @reviews.reverse.each do |review|  %>
			<div class="well well-sm">
				<% user_id = review.user_id %>
					<% author = User.find(user_id) %>
				<ul class='list-unstyled'>
					<li class='list-unstyled'>
						<h5>Posted by <%= author.username %> on <%= review.created_at.strftime("%B %d, %Y") %></h5>
						<h5><%= review.body %></h5>
							<div class="row">
								<div class="col-xs-6 col-sm-3">
									Programming<br>
									<div class="star-rating-pro" data-score=<%= review.programming %>></div>
								</div>
								<div class="col-xs-6 col-sm-3">
									Community<br>
									<div class="star-rating-com" data-score=<%= review.community %>></div>
								</div>
								<div class="col-xs-6 col-sm-3">
									Value<br>
									<div class="star-rating-fac" data-score=<%= review.facility %>></div>
								</div>
								<div class="col-xs-6 col-sm-3">
									Facility<br>
									<div class="star-rating-val" data-score=<%= review.value %>></div>
								</div>
							</div>
							<% if @user %>
							<span class="pull-right">
	      				<%= link_to '', "/reviews/#{review.id}/edit", class: 'ion ion-edit' %>
	     				</span>
	     				<% end %>					
	     		</li>
				</ul>
	  	</div> <!-- END WELL -->
	  	<% end %> <!-- end show reviews -->
		</div> <!-- END COL--><!-- end of reviews show -->	
	</div> <!-- end of row 3 col 1 -->
	<% end %>
	<% end %>
</div><!-- end of container -->



<!-- script for making rating on stars -->
<script>
	$('#star-rating-pro').raty({ 
		// path: '/assets/', 
		scoreName: 'review[programming]'
	});
</script>
<script>
	$('#star-rating-fac').raty({
		// path: '/assets/', 
		scoreName: 'review[facility]'
	});
</script>
<script>
	$('#star-rating-val').raty({
		// path: '/assets/', 
		scoreName: 'review[value]'
	});
</script>
<script>
	$('#star-rating-com').raty({
		// path: '/assets/', 
		scoreName: 'review[community]'
	});
</script>
<!-- Script for displaying rating -->
<script>
	$('.star-rating-pro').raty({
		// path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-fac').raty({
		// path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-val').raty({
		// path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>
<script>
	$('.star-rating-com').raty({
		// path: '/assets/', 
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>

<script type='text/javascript'>
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @gym.lat %>,
      "lng": <%= @gym.long %>,
      "picture": {
        "url": "http://google-maps-icons.googlecode.com/files/gym.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "<%= @gym.address %>"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(14);
});
</script>
<script>
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script>