config/routes.rb
Rails.application.routes.draw do
  
  root 'gyms#index'

  resources :gyms 
  resources :reviews

  get 'sessions/new'

  get 'sessions/create'
  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/signup", to: "users#new", as: "signup"
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :users

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def create
		@review = Review.new(review_params)
			if @review.save
        @gym = Gym.find(@review.gym_id)
        if @gym
          @gym.all_total_ratings
        else 
          puts "no gym found"
        end
				redirect_to :back
			end
	end

	def new
		@user = current_user
		@review = Review.new	
	end

	def edit
    @user = current_user
    @review = Review.find(params[:id])
     if current_user
      if @review.save
      end
      end
  end

  def update
    @review = Review.find(params[:id])
    @gym = Gym.find(@review.gym_id)
    @user = current_user
    if current_user
      @review.update_attributes(review_params)
      @gym.all_total_ratings
      redirect_to @review.gym 
    else
    end
  end

  def destroy
    # find current user
    @user = current_user
    # find post to delete
    @review = Review.find(params[:id])
    gym = Gym.find(@review.gym_id)
    gym.all_total_ratings
    # destroy post
    @gym = @review.gym
    @review.destroy
    redirect_to @gym
  end

	private
	
	def review_params
		params.require(:review).permit(:gym_id, :user_id, :body, :programming, :community, :value, :schedule, :facility, :trainers, :weightlifting_focus, :metcon_focus)
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
	
end

app/views/reviews/edit.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for @review do |r| %>
      <!-- error message -->
      <% if @review_edit_error %>
        <div class="alert alert-info text-center alert-danger"><%= flash[:error] %></div>
      <% end %>
      <h2> Edit Review </h2>
        <%= r.text_area :body, class: "form-control", autofocus: true %>
      <br>
      <div class="check-boxes">
        <%= r.check_box(:weightlifting_focus) %> <strong>Weightlifting Focus</strong>
        <%= r.check_box(:metcon_focus) %> <strong>Metcon Focus</strong>
      </div>
       <div class="ratings">
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            Programming<br>
            <div id="star-rating-pro"></div>
          </div>
          <div class="col-xs-6 col-sm-3">
            Community<br>
            <div id="star-rating-com"></div>
          </div>
          <div class="col-xs-6 col-sm-3">
            Value<br>
            <div id="star-rating-val"></div>
          </div>
          <div class="col-xs-6 col-sm-3">
            Facility<br>
            <div id="star-rating-fac"></div>
          </div>
        </div>
        </p>
        <span class="pull-right">
         <%= r.submit 'Submit', value: "Submit", class: "btn btn-primary" %> 
          <%= link_to 'Delete', review_path, method: :delete, class: "btn btn-danger" %>
        </span>
      <% end %>
    </div>
</div>

<!-- script for making rating on stars -->
<script>
  $('#star-rating-pro').raty({
    // path: '/assets/', 
    scoreName: 'review[programming]'
  });
</script>
<script>
  $('#star-rating-fac').raty({
    // path: '/assets/', 
    scoreName: 'review[facility]'
  });
</script>
<script>
  $('#star-rating-val').raty({
    // path: '/assets/', 
    scoreName: 'review[value]'
  });
</script>
<script>
  $('#star-rating-com').raty({
    // path: '/assets/', 
    scoreName: 'review[community]'
  });
</script>
<!-- Script for displaying rating -->

app/views/reviews/new.html.erb
<div class="container">
	<div class="row">
		<!-- NEW REVIEW FORM -->
			<div class="col-md-6 well"><!-- column 2 row 1 -->  
				<h5 class="text-center">Write a Review</h5>
					<%= form_for @review do |r| %>
						<%= r.hidden_field :gym_id, :value => @gym.id %>
						<%= r.hidden_field :user_id, :value => @user.id %>
						<%= r.text_area :body, class: "form-control", autofocus: true, placeholder: "Tell us about your experience here!" %>
				<br>
				<div class="check-boxes">
					<div class="table-responsive">
						<div class="table table-condensed">
							<table style="width:80%">
				  			<tr>
				    			<td><%= r.check_box(:weightlifting_focus) %>Weightlifting Focus</td>
									<td><%= r.check_box(:metcon_focus) %> Metcon Focus</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
			<div class="ratings">
				<div class="table-responsive">
					<div class="table table-condensed">
						<table style="width:100%">
					  		<tr>
					    		<td>Programming</td>
									<td>Community</td>
									<td>Facility</td>
									<td>Value</td>
					  		</tr>
					  		<tr>
					  			<td><div id="star-rating-pro"></div> </td>
					  			<td><div id="star-rating-com"></div> </td>
					  			<td><div id="star-rating-fac"></div> </td>
					  			<td><div id="star-rating-val"></div> </td>
				  			</tr>
				  		</table>
						</div>
					</div>	
				</div>
				<div class="text-right">
				<%= r.submit 'review', value: "Post!", class: "btn btn-primary btn-sm" %>
				</div>
		</div><!-- END OF COL -->
	</div><!-- END OF ROW -->
</div>
<% end %>		<!-- END OF NEW REVIEW FORM -->